### ISSUE TITLE
Steering angle values

### ISSUE THREAD

**Issue by jHaselberger** [commaai/research#48]
I've downloaded the dataset and analyzed some of the test drives.
Right now I'm wondering about the steering_angle value ranges.

They are going from about -4500 to 4500. 
What is the unit of the recorded angles?

**Comment by cardwing** [comment]
I guess the steering angle is multiplied by 10.

**Comment by cardwing** [comment]
In view_steering_model.py, you see that the angle_steers is divided by 10, which indicates what I have said above (In line 122).

**Comment by ahmedyahia3393** [comment]
This error (ValueError: bad marshal data (unknown type code)) result when trying to execute the view steering model.py
here is the result from the cmd prompt

Traceback (most recent call last):
File "C:\Users\lenovo\Anaconda3\lib\site-packages\keras\utils\generic_utils.py
", line 229, in func_load
raw_code = codecs.decode(code.encode('ascii'), 'base64')
UnicodeEncodeError: 'ascii' codec can't encode character '\xe0' in position 46:
ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "view_steering_model.py", line 94, in 
model = model_from_json(json.load(jfile))
File "C:\Users\lenovo\Anaconda3\lib\site-packages\keras\models.py", line 349,
in model_from_json
return layer_module.deserialize(config, custom_objects=custom_objects)
File "C:\Users\lenovo\Anaconda3\lib\site-packages\keras\layers_init_.py", l
ine 55, in deserialize
printable_module_name='layer')
File "C:\Users\lenovo\Anaconda3\lib\site-packages\keras\utils\generic_utils.py
", line 144, in deserialize_keras_object
list(custom_objects.items())))
File "C:\Users\lenovo\Anaconda3\lib\site-packages\keras\models.py", line 1349,
in from_config
layer = layer_module.deserialize(conf, custom_objects=custom_objects)
File "C:\Users\lenovo\Anaconda3\lib\site-packages\keras\layers_init_.py", l
ine 55, in deserialize
printable_module_name='layer')
File "C:\Users\lenovo\Anaconda3\lib\site-packages\keras\utils\generic_utils.py
", line 144, in deserialize_keras_object
list(custom_objects.items())))
File "C:\Users\lenovo\Anaconda3\lib\site-packages\keras\layers\core.py", line
711, in from_config
function = func_load(config['function'], globs=globs)
File "C:\Users\lenovo\Anaconda3\lib\site-packages\keras\utils\generic_utils.py
", line 234, in func_load
code = marshal.loads(raw_code)
ValueError: bad marshal data (unknown type code)

**Comment by steve7158** [comment]
What i foud was that the max steering angle in 5008, so the steering aangle has a range in between -5000 to +5000. So according to me we should divide it by 100 to get angles in between(-50 to +50) 
The angle at which the front wheels are ALLOWED to turn really varies with what the auto’s engineers deemed allowable. On some cars this may be 30 degrees, on others it may be 50. The logic behind the maximum is a bit more complicated.
from(https://www.quora.com/Why-cant-a-cars-wheels-turn-more-than-45-degrees)
I hope this helps.
